### ISSUE TITLE
Change the map to get rid of modern political borders / restore to ancient map

### ISSUE THREAD

**Issue by sbrennanmcmahon** [davidfdriscoll/greeklyricpoets#323]
I think the old map (shown on the youtube video) is from the Ancient World Mapping Centre: http://awmc.unc.edu/wordpress/
Another resource: Barrington Atlas
Ideally we would have ancient borders.
We probably don't want to change the map based on where we are on the slider.

**Comment by AllynWaller** [comment]
This might also be good to use: https://awmc.unc.edu/wordpress/alacarte/

**Comment by AllynWaller** [comment]
Looks like the basemap options are limited to CARTO and Google Maps: https://docs.carto.com/carto-user-manual/maps/map-settings/#basemaps 

I can change it if I can get into CARTO.

**Comment by AllynWaller** [comment]
Switched it to a satellite view.
